/* external-download-manager.h generated by valac 0.16.0, the Vala compiler, do not modify */


#ifndef __DEFAULT_EXTENSIONS_EXTERNAL_DOWNLOAD_MANAGER_H__
#define __DEFAULT_EXTENSIONS_EXTERNAL_DOWNLOAD_MANAGER_H__

#include <glib.h>

G_BEGIN_DECLS



KatzeArray* extension_init (void);


G_END_DECLS

#endif
