/* external-download-manager.vapi generated by valac 0.16.0, do not modify. */

namespace EDM {
}
[CCode (cheader_filename = "external-download-manager.h")]
public static Katze.Array extension_init ();
